<?php
# PHPKIT WCMS | Web Content Management System
#
#
# YOU ARE NOT AUTHORISED TO CREATE ILLEGAL COPIES OF THIS
# FILE AND/OR TO REMOVE THIS INFORMATION
#
# SIE SIND NICHT BERECHTIGT, UNRECHTMÄSSIGE KOPIEN DIESER
# DATEI ZU ERSTELLEN UND/ODER DIESE INFORMATIONEN ZU ENTFERNEN
#
# This file / the PHPKIT software is no freeware! For further 
# information please visit our website or contact us via email:
#
# Diese Datei / die PHPKIT Software ist keine Freeware! Für weitere
# Informationen besuchen Sie bitte unsere Website oder kontaktieren uns per E-Mail:
#
# email     : info@phpkit.com
# website   : http://www.phpkit.com
# licence   : http://www.phpkit.com/licence
# copyright : Copyright (c) 2002-2009 mxbyte gbr | http://www.mxbyte.com


return array(
#welcome / start page
'main' => array(
		'id'			=> 'main',
		'pid'			=> '',
		'sorting'		=> 0,
		'lkey'			=> 'welcome_page',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'main',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
#contents
'contents' => array(
		'id'			=> 'contents',
		'pid'			=> '',
		'sorting'		=> 1,		
		'lkey'			=> 'contents',
		'lscope'		=> 'content',
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'contents_overview' => array(
		'id'			=> 'contents_overview',
		'pid'			=> 'contents',
		'sorting'		=> 0,
		'lkey'			=> 'overview',
		'lscope'		=> 'content',
		'target'		=> '',
		'lnkpath'		=> 'contentarchive',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'contents_compose' => array(
		'id'			=> 'contents_compose',
		'pid'			=> 'contents',
		'sorting'		=> 1,		
		'lkey'			=> 'compose_content',
		'target'		=> '',
		'lnkpath'		=> 'contentcompose',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'contents_cat' => array(
		'id'			=> 'contents_cat',
		'pid'			=> 'contents',
		'sorting'		=> 2,		
		'lkey'			=> 'categories',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'contentcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'contents_catadd' => array(
		'id'			=> 'contents_catadd',
		'pid'			=> 'contents',
		'sorting'		=> 3,		
		'lkey'			=> 'add_category',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'contentcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> 'catselect=new',		
		'permission'	=> '',
		),	
'contents_topics' => array(
		'id'			=> 'contents_topics',
		'pid'			=> 'contents',
		'sorting'		=> 4,		
		'lkey'			=> 'topics',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'contentcategory',
		'lnkmode'		=> 'theme',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'contents_transmit' => array(
		'id'			=> 'contents_transmit',
		'pid'			=> 'contents',
		'sorting'		=> 5,		
		'lkey'			=> 'transmittals',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'contentsubmited',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
#FAQ
'faq' => array(
		'id'			=> 'faq',
		'pid'			=> '',
		'sorting'		=> 2,		
		'lkey'			=> 'faq',
		'lscope'		=> '',		
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'faq_overview' => array(
		'id'			=> 'faq_overview',
		'pid'			=> 'faq',
		'sorting'		=> 0,
		'lkey'			=> 'overview',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'faqarchive',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),	
'faq_compose' => array(
		'id'			=> 'faq_compose',
		'pid'			=> 'faq',
		'sorting'		=> 1,		
		'lkey'			=> 'compose_entry',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'faqcompose',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'faq_cat' => array(
		'id'			=> 'faq_cat',
		'pid'			=> 'faq',
		'sorting'		=> 2,		
		'lkey'			=> 'categories',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'faqcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'faq_catadd'=>array(
		'id'			=> 'faq_catadd',
		'pid'			=> 'faq',
		'sorting'		=> 3,		
		'lkey'			=> 'add_category',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'faqcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> 'catid=new',		
		'permission'	=> '',
	),	
#forums
'forums' => array(
		'id'			=> 'forums',
		'pid'			=> '',
		'sorting'		=> 4,
		'lkey'			=> 'forums',
		'lscope'		=> '',		
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'forums_cat' => array(
		'id'			=> 'forum_cat',
		'pid'			=> 'forums',
		'sorting'		=> 0,
		'lkey'			=> 'categories',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'forumcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'forums_catadd' => array(
		'id'			=> 'forums_catadd',
		'pid'			=> 'forums',
		'sorting'		=> 1,		
		'lkey'			=> 'add_category',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'forumcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> 'editcat=new',	
		'permission'	=> '',
		),	
'forums_info' => array(
		'id'			=> 'forums_info',
		'pid'			=> 'forums',
		'sorting'		=> 2,		
		'lkey'			=> 'forumsinformations',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'foruminfo',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'forums_ranks' => array(
		'id'			=> 'forums_ranks',
		'pid'			=> 'forums',
		'sorting'		=> 3,		
		'lkey'			=> 'forumsranks',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'forumrank',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
#guestbook
#votings
'polls' => array(
		'id'			=> 'polls',
		'pid'			=> '',
		'sorting'		=> 6,		
		'lkey'			=> 'polls',
		'lscope'		=> '',		
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'polls_overview' => array(
		'id'			=> 'polls_overview',
		'pid'			=> 'polls',
		'sorting'		=> 0,		
		'lkey'			=> 'overview',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'pollarchive',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'polls_add' => array(
		'id'			=> 'polls_add',
		'pid'			=> 'polls',
		'sorting'		=> 1,		
		'lkey'			=> 'create_poll',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'pollcompose',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
#navigation
'menu' => array(
		'id'			=> 'menu',
		'pid'			=> '',
		'sorting'		=> 7,		
		'lkey'			=> 'navigation',
		'lscope'		=> '',
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'menu_cat' => array(
		'id'			=> 'menu_cat',
		'pid'			=> 'menu',
		'sorting'		=> 0,		
		'lkey'			=> 'categories',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'navigationcategory',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'menu_links' => array(
		'id'			=> 'menu_links',
		'pid'			=> 'menu',
		'sorting'		=> 1,		
		'lkey'			=> 'links',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'navigationlink',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
#users
'users' => array(
		'id'			=> 'users',
		'pid'			=> '',
		'sorting'		=> 8,		
		'lkey'			=> 'users',
		'lscope'		=> '',		
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'users_overview' => array(
		'id'			=> 'users_overview',
		'pid'			=> 'users',
		'sorting'		=> 0,		
		'lkey'			=> 'overview',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'userslist',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
	),
'users_accountadd' => array(
		'id'			=> 'users_accountadd',
		'pid'			=> 'users',
		'sorting'		=> 1,		
		'lkey'			=> 'create_useraccount',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'useredit',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'users_fields' => array(
		'id'			=> 'users_fields',
		'pid'			=> 'users',
		'sorting'		=> 2,
		'lkey'			=> 'profilefields',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'userprofilefields',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'users_groups' => array(
		'id'			=> 'users_groups',
		'pid'			=> 'users',
		'sorting'		=> 3,		
		'lkey'			=> 'usergroups',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'usergroup',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'users_avatars' => array(
		'id'			=> 'users_avatars',
		'pid'			=> 'users',
		'sorting'		=> 4,
		'lkey'			=> 'useravatars',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'useravatar',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
#miscellaneous
'misc' => array(
		'id'			=> 'misc',
		'pid'			=> '',
		'sorting'		=> 9,		
		'lkey'			=> 'miscellaneous',
		'lscope'		=> '',		
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'misc_adview' => array(
		'id'			=> 'misc_adview',
		'pid'			=> 'misc',
		'sorting'		=> 0,
		'lkey'			=> 'advertising',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'advertising',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'comments' => array(
		'id'			=> 'comments',
		'pid'			=> 'misc',
		'sorting'		=> 1,		
		'lkey'			=> 'comments',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'comment',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'database' =>array(
		'id'			=> 'database',
		'pid'			=> 'misc',
		'sorting'		=> 2,		
		'lkey'			=> 'database',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'database',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),	
'media' => array(
		'id'			=> 'media',
		'pid'			=> 'misc',
		'sorting'		=> 3,		
		'lkey'			=> 'images',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'mediaarchive',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
/*'misc_mailer' => array(
		'id'			=> 'misc_mailer',
		'pid'			=> 'misc',
		'sorting'		=> 4,		
		'lkey'			=> 'infomailer',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'mailer',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),*/
'misc_smilies' => array(
		'id'			=> 'misc_smilies',
		'pid'			=> 'misc',
		'sorting'		=> 5,		
		'lkey'			=> 'smilies',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'smilies',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'layout_designs' => array(
		'id'			=> 'layout_designs',
		'pid'			=> 'misc',
		'sorting'		=> 6,		
		'lkey'			=> 'styles',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'style',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'layout_tpls' => array(
		'id'			=> 'layout_tpls',
		'pid'			=> 'misc',
		'sorting'		=> 7,		
		'lkey'			=> 'templates',
		'lscope'		=> '',	
		'target'		=> '',
		'lnkpath'		=> 'templates',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
	),
#informationen_and_statistics		
'stats' => array(
		'id'			=> 'stats',
		'pid'			=> '',
		'sorting'		=> 10,		
		'lkey'			=> 'informationen_and_statistics',
		'lscope'		=> '',		
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'stats_pageviews' => array(
		'id'			=> 'stats_pageviews',
		'pid'			=> 'stats',
		'sorting'		=> 0,		
		'lkey'			=> 'pageimpressions',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'pageimpressions',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),		
'stats_referrer' => array(
		'id'			=> 'stats_referrer',
		'pid'			=> 'stats',
		'sorting'		=> 1,		
		'lkey'			=> 'refererlinks',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'referer',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'stats_systeminfo' => array(
		'id'			=> 'stats_systeminfo',
		'pid'			=> 'stats',
		'sorting'		=> 2,		
		'lkey'			=> 'systeminformations',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'sysinfo',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
#configuration
'config' => array(
		'id'			=> 'config',
		'pid'			=> '',
		'sorting'		=> 90,		
		'lkey'			=> 'configuration',
		'lscope'		=> '',
		'target'		=> 'NAVIGATION',
		'lnkpath'		=> '',
		'lnkmode'		=> '',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'config_all' => array(
		'id'			=> 'config_all',
		'pid'			=> 'config',
		'sorting'		=> 0,		
		'lkey'			=> 'all_settings',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_master' => array(
		'id'			=> 'config_master',
		'pid'			=> 'config',
		'sorting'		=> 1,		
		'lkey'			=> 'master_data',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'master',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_meta' => array(
		'id'			=> 'config_meta',
		'pid'			=> 'config',
		'sorting'		=> 2,		
		'lkey'			=> 'meta_settings',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'meta',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_mailer'	=> array(
		'id'			=> 'config_mailer',
		'pid'			=> 'config',
		'sorting'		=> 3,		
		'lkey'			=> 'mailer_settings',
		'lscope'		=> '',	
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'mailer',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_frontpage' => array(
		'id'			=> 'config_frontpage',
		'pid'			=> 'config',
		'sorting'		=> 4,		
		'lkey'			=> 'frontpage_settings',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'frontpage',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),		
'config_censor' => array(
		'id'			=> 'config_censor',
		'pid'			=> 'config',
		'sorting'		=> 5,		
		'lkey'			=> 'censor_settings',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'censor',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'config_notify' => array(
		'id'			=> 'config_notify',
		'pid'			=> 'config',
		'sorting'		=> 6,		
		'lkey'			=> 'notify_settings',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'notify',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_register' => array(
		'id'			=> 'config_register',
		'pid'			=> 'config',
		'sorting'		=> 7,		
		'lkey'			=> 'register_settings',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'register',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'config_user' => array(
		'id'			=> 'config_user',
		'pid'			=> 'config',
		'sorting'		=> 8,		
		'lkey'			=> 'user_settings',
		'lscope'		=> 'user',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'member',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_avatars' => array(
		'id'			=> 'config_avatars',
		'pid'			=> 'config',
		'sorting'		=> 9,		
		'lkey'			=> 'avatar_settings',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'avatar',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_referrer' => array(
		'id'			=> 'config_referrers',
		'pid'			=> 'config',
		'sorting'		=> 10,		
		'lkey'			=> 'referer_settings',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'referer',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_maintenance' => array(
		'id'			=> 'config_maintenance',
		'pid'			=> 'config',
		'sorting'		=> 11,		
		'lkey'			=> 'maintenance_mode',
		'lscope'		=> 'except',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'offline',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_comments' => array(
		'id'			=> 'config_comments',
		'pid'			=> 'config',
		'sorting'		=> 12,		
		'lkey'			=> 'comment_settings',
		'lscope'		=> '',		
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'comment',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_guestbook' => array(
		'id'			=> 'config_guestbook',
		'pid'			=> 'config',
		'sorting'		=> 13,		
		'lkey'			=> 'guestbook_settings',
		'lscope'		=> 'guestbook',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'guestbook',
		'lnkadd'		=> '',
		'permission'	=> '',
		),
'config_contents' => array(
		'id'			=> 'config_contents',
		'pid'			=> 'config',
		'sorting'		=> 14,		
		'lkey'			=> 'content_settings',
		'lscope'		=> 'content',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'content',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_forums' => array(
		'id'			=> 'config_forums',
		'pid'			=> 'config',
		'sorting'		=> 15,		
		'lkey'			=> 'forum_settings',
		'lscope'		=> 'forum',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'forum',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_rssfeeds' => array(
		'id'			=> 'config_rssfeeds',
		'pid'			=> 'config',
		'sorting'		=> 16,		
		'lkey'			=> 'rss_feed_settings',
		'lscope'		=> 'rss',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'rssfeed',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),
'config_socialnetworks' => array(
		'id'			=> 'config_socialnetworks',
		'pid'			=> 'config',
		'sorting'		=> 17,		
		'lkey'			=> 'social_networks_settings',
		'lscope'		=> 'social',
		'target'		=> '',
		'lnkpath'		=> 'config',
		'lnkmode'		=> 'social',
		'lnkadd'		=> '',		
		'permission'	=> '',
		),		
'licencekey' => array(
		'id'			=> 'licencekey',
		'pid'			=> '',
		'sorting'		=> 99,
		'lkey'			=> 'licencekey',
		'lscope'		=> '',
		'target'		=> '',
		'lnkpath'		=> 'licencekey',
		'lnkmode'		=> '',
		'lnkadd'		=> '',		
		'permission'	=> '',
		)
);
?>